name: FastAliases
description: Aliases plugin for spigot
author: CoderGautamYT
main: com.codergautamyt.fastaliases.FastAliases
version: 1.0
commands:
  fastaliases:
    description: Main command
    usage: /<command>
